### ISSUE TITLE
question about servername field

### ISSUE THREAD

**Issue by iloahz** [sagi/node-dns-over-tls#10]
For below code:
```
    if (!options.host || !options.servername || !options.name) {
      throw new Error('At least host, servername and name must be set.');
    }
```
Is `servername` a required field, cause sometimes we only know the IP address.

**Comment by sagi** [comment]
Hey @iloahz,

DNS-over-**`TLS`** requires the `servername` option for TLS hostname authentication. Technically, we can use an IP address to establish a TLS session without authenticating the hostname, but that would mean that `node-dns-over-tls`'s security would depend on how the developer uses it - a scenario I would rather avoid.
